services:
  postgres:
    image: postgres:16-alpine
    container_name: film_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # автосиды выполняются при первом создании тома
      - ./backend/test/prac.init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
      - ./backend/test/prac.films.sql:/docker-entrypoint-initdb.d/02_films.sql:ro
      - ./backend/test/prac.schedules.sql:/docker-entrypoint-initdb.d/03_schedules.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [film_network]
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: film_pgadmin
    env_file: [.env]
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on: [postgres]
    networks: [film_network]
    restart: unless-stopped

  frontend-builder:
    build:
      context: ./frontend
    image: ghcr.io/annpikova/film-frontend:latest
    volumes:
      - frontend_dist:/output
    networks: [film_network]
    restart: "no"

  backend:
    build:
      context: ./backend
    image: ghcr.io/annpikova/film-backend:latest
    container_name: film_backend
    env_file: [.env]
    environment:
      NODE_ENV: development
      LOGGER_TYPE: ${LOGGER_TYPE:-dev}     # dev | json | tskv
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      # если DATABASE_URL не задан — возьмётся дефолт
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./backend/public:/app/public
    depends_on:
      postgres:
        condition: service_healthy
    networks: [film_network]
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    image: ghcr.io/annpikova/film-nginx:latest
    container_name: film_nginx
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend-builder
    networks: [film_network]
    restart: unless-stopped

networks:
  film_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  frontend_dist:
